### ISSUE TITLE
Error 400 when calling restlet 

### ISSUE THREAD

**Issue by gainskills** [jmagnusson/netsuite#11]
I did a test on restlet function, and got the error:

```
Traceback (most recent call last):
  File "...test_let.py", line 12, in <module>
    nsResRes = nsResReq.request(script_id=642, deploy=1)
  File "...netsuite_jjorissen52/netsuite/restlet.py", line 52, in request
    util.raise_for_status_with_body(resp)
  File "...netsuite_jjorissen52/netsuite/util.py", line 51, in raise_for_status_with_body
    raise ex
  File "...netsuite_jjorissen52/netsuite/util.py", line 44, in raise_for_status_with_body
    response.raise_for_status()
  File ".../venv/lib/python3.8/site-packages/requests/models.py", line 965, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fake-id.restlets.api.netsuite.com/app/site/hosting/restlet.nl?script=642&deploy=1
```

Any suggestions would be greatly appreciated

**Comment by gainskills** [comment]
@jjorissen52

**Comment by jjorissen52** [comment]
@gainskills Hello, no worries at all.

I have never used this portion of the client library, but after giving `netsuite/restlet.py` a once over, it looks like the culprit would be here:

```
class NetsuiteRestlet:

    _restlet_path_tmpl = \
        '/app/site/hosting/restlet.nl?script={script_id}&deploy={deploy}'

    def __init__(self, config, *, hostname=None):
        self.__config = config
        self.__hostname = hostname or self._make_default_hostname()
        self._request_session = self._make_request_session()
```

In your situation, whatever is initializing the instance of `NetsuiteRestlet` is calling doing it like below:

`NetsuiteRestlet(hostname="fake-id.restlets.api.netsuite.com")`
or like this
`NetsuiteRestlet()`.

The latter instance would cause the below function to set your `hostname` according to the `account` set in your config.

```
def _make_default_hostname(self):
        account_slugified = self.config.account.lower().replace('_', '-')
        return f'{account_slugified}.restlets.api.netsuite.com'
```

If you look in the config object, you can see:

```
account = None
    """The NetSuite account ID"""
```

My guess is that your `config.ini` file has account = fake-id in it somewhere. The actual account must correspond to your netsuite deployment's ID. If this isn't it, I would have to see more about what you are doing to make n assessment.

**Comment by jjorissen52** [comment]
@gainskills now that I think about it, it's more likely that you anonymized your logs, and in doing so you changed out your real id with a fake one. In that case, I have no clue.
