### ISSUE TITLE
NetsuiteRestlet doesn't support non-POST requests

### ISSUE THREAD

**Issue by GPHemsley** [jmagnusson/netsuite#15]
RESTlets can be designed to respond to most HTTP verbs, including GET, but this library only supports POST.

**Comment by merit-sno** [comment]
Please confirm that you are using v0.4.1.  PyPi is behind the Git version and currently providing v0.4.0.

**Comment by GPHemsley** [comment]
No, I am using the version available on PyPI.

But it doesn't matter, because the code is the same:
https://github.com/jmagnusson/netsuite/blob/37feab01570753e101ecfd32eee2c0ddd687f8e5/netsuite/restlet.py#L70

**Comment by GPHemsley** [comment]
FWIW, this is how I'm working around it (as well as the lack of support for the Authorization header authentication method):
```python
class NetSuiteRestlet(netsuite.restlet.NetsuiteRestlet):  # type: ignore
	def _make_headers(self) -> Dict[str, str]:
		headers: Dict[str, str] = super()._make_headers()

		headers["Authorization"] = " ".join([
			"NLAuth",
			",".join([
				f"nlauth_email={self.config.email}",
				f"nlauth_signature={self.config.password}",
				f"nlauth_account={self.config.account}",
				f"nlauth_role={self.config.application_id}",
			]),
		])

		return headers

	def _make_request_session(self) -> requests.Session:
		# XXX: This is a hack on top of a hack.
		class Session(requests.Session):
			def post(self, *args: Any, **kwargs: Any) -> requests.Response:
				method = "POST"

				if "method" in kwargs:
					method = kwargs["method"]
					del kwargs["method"]

				return self.request(method, *args, **kwargs)

		return Session()
```

**Comment by jmagnusson** [comment]
@GPHemsley Please submit a PR if you would like to have this fixed (I'm very limited on time...).
