### ISSUE TITLE
ConnectionError: Max retries exceeded

### ISSUE THREAD

**Issue by Shubham-S-Yadav** [jmagnusson/netsuite#21]
Hi, I'm new to NetSuite, I'm trying to implement netsuite library for integrating SOAP in my application. I tried out below code but getting ConnectionError. Please check the attached file to which has trace out of the error. Also, it will be a great help if you add documentation for programmatic implementation.

Code:
import netsuite

config = netsuite.config.from_ini('D:/netsuite/config.ini')
client = netsuite.NetSuite(config=config)

client.getList("customer", internalIds=[422])

Error:
[error.txt](https://github.com/jmagnusson/netsuite/files/4966067/error.txt)

**Comment by jmagnusson** [comment]
It looks like you quoted the `account` setting twice:

ConnectionError: HTTPSConnectionPool(host='__%224973434-sb1%22__.suitetalk.api.netsuite.com', port=443)
