### ISSUE TITLE
Empty POST requests

### ISSUE THREAD

**Issue by jtalmi** [jmagnusson/netsuite#22]
Hey, I love the library but I'm having an issue making POST requests. GET requests work fine. I run:

`cat test.json | netsuite rest-api post /record/v1/salesorder -`

and I know the request is solid because test.json works fine in Postman

But I receive:

```
netsuite.rest_api.NetsuiteAPIRequestError: HTTP400 - {"type":"https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1","title":"Please enter a value for entity","status":400,"o:errorCode":"FIELD_PARAM_REQD"}
```
And when I check the logs in netsuite UI, the request body is empty.

I've tried to debug but I'm not too familiar with asyncio. Would greatly appreciate if someone could help out with this!

**Comment by jmagnusson** [comment]
Thanks for your bug report @jtalmi, this was fixed in #26 (which was released with v0.6.0)
