### ISSUE TITLE
Cannot use versions other than 2017.2

### ISSUE THREAD

**Issue by wwatkinson** [jmagnusson/netsuite#4]
The client supports inputting a version, but the passport has the url hard coded to 2017.2 when retrieving the TokenPassport and the TokenPassportSignature, so if you try to create a client with any version besides 2017.2 it will error whenever it tries to create a passport to make a request.

**Comment by jmagnusson** [comment]
Hi @wwatkinson,

@matmunn's contribution in #2 should fix this for you. (Unable to look at/merge for the time being though)

**Comment by WesleyBatista** [comment]
I noticed the same issue. Would be very appreciated to have the PR #2 merged 

Hope you find time soon :)

**Comment by jmagnusson** [comment]
Fixed in #5
