### ISSUE TITLE
Search method errors if there are no results

### ISSUE THREAD

**Issue by wwatkinson** [jmagnusson/netsuite#9]
If no results are returned by the search method it results in an error:
\netsuite\client.py", line 555, in <lambda>
    extract=lambda resp: resp['recordList']['record'],
TypeError: 'NoneType' object is not subscriptable

There are frequent use cases, like a scheduled search, where there will be no results. In these cases it would make more sense for an empty list to be returned instead of the code erroring out.

**Comment by jmagnusson** [comment]
Thanks for your report @wwatkinson. I'll see what I can do in the upcoming months (full schedule atm)

**Comment by wwatkinson** [comment]
Appreciate you creating and maintaining this. I was able to to fix by throwing a try/except around the extraction (line 70 in client.py), so if the extraction does not point to any data it returns None:

            if extract is not None:
                logger.debug(response)
                try:
                    response = extract(response)
                except:
                    response = None

Happy to submit a pull request, but understand it'll take time for you to test/decide if you want to use this solution.

**Comment by ismaban** [comment]
Hi guys,
I have been trying to use the `search` method to pull results from a Saved Search (Customer) and I get the same error as @wwatkinson, but this time the Search Results do contain data. I have confirmed that by looking at the WebServices logs in Netsuite. The Saved Search has 6711 results.

The error I get is: `TypeError: 'NoneType' object is not subscriptable `

My code snippet is:
```
ns = netsuite.NetSuite(**{
    'config': {
        'account': 'XXXXXX',
        'consumer_key': 'XXXXXXX',
        'consumer_secret': 'XXXXXXX',
        'token_id': 'XXXXXXX',
        'token_secret': 'XXXXXXX',
    },
    'version': '2018.1.0',
})

type(ns)
# returns "netsuite.client.NetSuite"

a = ns.Relationships.CustomerSearchAdvanced(savedSearchId='1360')
type(a)
# returns "zeep.objects.CustomerSearchAdvanced"
ns.search(a)
```

The last line returns
```
TypeError                                 Traceback (most recent call last)
 in ()
----> 1 ns.search(a)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netsuite/client.py in wrapper(self, *args, **kw)
     77 
     78             if extract is not None:
---> 79                 response = extract(response)
     80 
     81             return response

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/netsuite/client.py in (resp)
    553     @WebServiceCall(
    554         'body.searchResult',
--> 555         extract=lambda resp: resp['recordList']['record'],
    556     )
    557     def search(self, record: CompoundValue) -> List[CompoundValue]:

TypeError: 'NoneType' object is not subscriptable
```

Would you be able to advise if this is a bug in the "netsuite" module...or am I just doing something wrong?

Thanks in advance for your help and feedback.

**Comment by wwatkinson** [comment]
@ismaban The search method in this package looks for the search results in Body.searchResult.recordList.record, but saved searches return results at Body.searchResult.searchRowList.searchRow as you can see in webservices logs. Since the path specified in the search method is different than what is in the returned payload it is erroring out. To get the saved search results I would use the request method:
`a = ns.Relationships.CustomerSearchAdvanced(savedSearchId='1360')
ns.request('search', a)`
This will return the full payload and you can specify the path to get the results yourself.

**Comment by ismaban** [comment]
@wwatkinson : Thanks so much for your help here, that solved my problem

**Comment by jmagnusson** [comment]
Going to close this. Please submit a PR if you would like to have it fixed.
